kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs
provisioner: ceph.com/cephfs
parameters:
    monitors: __MONITORS__
    adminId: admin
    adminSecretName: ceph-secret
    adminSecretNamespace: "kube-system"
